name: "ll_project"
type: "python:3.13"

# Define the relationship key that Django will use
relationships:
    database: "postgresql:postgresql"

# Web configuration
web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

# Persistent disk size for the application
disk: 512

# Local mount for logs
mounts:
    "logs":
        source: local
        source_path: logs

# Build and deploy hooks
hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        
        mkdir -p logs
        python manage.py collectstatic --noinput
    deploy: |
        python manage.py migrate
