name: "ll_project"
type: "python:3.13"

dependencies:
    python3:
        gunicorn: "*"

relationships:
    database: "postgresql:postgresql"

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"

    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        python manage.py collectstatic --noinput

    deploy: |
        python manage.py migrate
